# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CL5_Artistry' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.5'
  # Pods for CL5_Artistry

  target 'CL5_ArtistryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CL5_ArtistryUITests' do
    # Pods for testing
  end

end
