# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PRRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
    pod 'Alamofire', '~> 5.5'
    pod 'SDWebImage', '~> 5.0'
    pod 'RxDataSources', '~> 5.0'
    pod 'Pure'
  # Pods for PRRxSwift

  target 'PRRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PRRxSwiftUITests' do
    # Pods for testing
  end

end
